### ISSUE TITLE
Availability of Training Data after Preprocessing and Checkpoints

### ISSUE THREAD

**Issue by ruian1** [mueller-franzes/MST#1]
Hi there, thank you for your great work on this project. I was wondering if it would be possible to share the training data after the preprocessing steps described in the paper, as well as the best checkpoints you obtained? I’d really appreciate it. Thanks!

**Comment by ruian1** [comment]
Hi, just following up here, it would be nice to have datasets mentioned below together with the ckpt used in the paper, I'm trying to reproduce the results from the paper, thanks

https://github.com/mueller-franzes/MST/blob/main/mst/data/datasets/dataset_3d_duke.py#L11
https://github.com/mueller-franzes/MST/blob/main/mst/data/datasets/dataset_3d_duke.py#L54

https://github.com/mueller-franzes/MST/blob/main/mst/data/datasets/dataset_3d_lidc.py#L11
https://github.com/mueller-franzes/MST/blob/main/mst/data/datasets/dataset_3d_lidc.py#L57

https://github.com/mueller-franzes/MST/blob/main/mst/data/datasets/dataset_3d_mrnet.py#L10
https://github.com/mueller-franzes/MST/blob/main/mst/data/datasets/dataset_3d_mrnet.py#L56

**Comment by tangoee139** [comment]
+1

**Comment by mueller-franzes** [comment]
Hi, thank you for your interest in the project. I can't share the data for legal reasons. However, I have uploaded the preprocessing scripts so you can download the data sets from the original sources and then run the scripts. 

The model weights are now available at Zenodo (link in the readme file).

**Comment by ruian1** [comment]
Thank you for providing the ckpts and data preprocessing script!

There is a follow-up question for loading the ckpt, since `best_checkpoint.json` was not provided, I tried the load function of `ResNet.load_from_checkpoint` as below, and got a bug, please help take a look, thanks!

```
from mst.models.resnet import ResNet
ckpt_path = "/root/projects/Medical_Slice_Transformer/runs/LIDC/ResNet/MST_LIDC.ckpt"
lidc_model = ResNet.load_from_checkpoint(ckpt_path)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/module.py", line 1582, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/core/saving.py", line 165, in _load_state
    obj = instantiator(cls, _cls_kwargs) if instantiator else cls(**_cls_kwargs)
  File "/root/projects/Medical_Slice_Transformer/mst/models/resnet.py", line 28, in __init__
    super().__init__(in_ch, out_ch, spatial_dims, **kwargs)
TypeError: BasicClassifier.__init__() got an unexpected keyword argument 'save_attn'
>>> ckpt_path = "/root/projects/Medical_Slice_Transformer/runs/LIDC/ResNet/MST_LIDC.ckpt"
```

**Comment by mueller-franzes** [comment]
Hi, the checkpoints refer to the MST model, not ResNet. Please try the following:
```
from mst.models.dino import DinoV2ClassifierSlice
ckpt_path = "/root/projects/Medical_Slice_Transformer/runs/LIDC/DinoV2ClassifierSlice/MST_LIDC.ckpt"
lidc_model = DinoV2ClassifierSlice.load_from_checkpoint(ckpt_path)
```

**Comment by llxlucy** [comment]
hi, in the dataset_3d_lidc.py, the use of lambda will cause the failure of pickle. And the solving method is define other functions to replace it. And I have already done this, there is still reports the same mistake.It's so frustraing.How did you solve this problem?
